### ISSUE TITLE
Migrate this repository to github.com/metanorma

### ISSUE THREAD

**Issue by opoudjis** [metanorma/itubib#2]
The repository github.com/metanorma has been set up to host all Metanorma related work. This is one such piece of work. While the migration will be slow (there is a lot to do, and a lot of interdependencies), we need to schedule migration for all related repositories.

Migration to Metanorma:

* Repost the repository to http://github.com/metanorma/X
  * This should be as simple as changing the following field in .git/config: `[remote "origin"]   url = https://github.com/riboseinc/metanorma-iso.git`. Refer https://help.github.com/en/articles/transferring-a-repository
* If this is a Ruby gem, change the address of the repository in the *.gemspec
* Delete all files but the Readme in the riboseinc repository
* Replace the Readme in the riboseinc repository with the message "Repository migrated to http://github.com/metanorma/X
* Update the links to the repository in any documentation you maintain
* Link the README in the new location to updated links for appveyor, CodeClimate, travis, etc. New links to travis should be to travis-ci.com, not travis-ci.org.
* Notify @opoudjis and @strogonoff when you have migrated the repository. They will then update the links to the repository in any documentation they maintain.

**Comment by andrew2net** [comment]
@ronaldtse I see similar issues in other repositories. Will, you unassing me on all of them?

**Comment by ronaldtse** [comment]
Hi @andrew2net , could you help update all the *bib repositories to reflect the new repo address? Thanks!

**Comment by andrew2net** [comment]
Hi @ronaldtse, yes, I can. But I don't understand. Should I update this repository and other where I was assigned by @opoudjis and then unassigned by you?

**Comment by ronaldtse** [comment]
I didn’t unassign anything... maybe it was due to the repo move?

**Comment by andrew2net** [comment]
@ronaldtse 
<img width="423" alt="2019-03-07 16 20 40" src="https://user-images.githubusercontent.com/5623890/53967158-f8178680-40f4-11e9-8f32-14a2c585bb10.png">

**Comment by ronaldtse** [comment]
I think this is because you haven't joined the "metanorma" org, so the transfer of the repo to the new organization automatically "unassigned" you.

**Comment by andrew2net** [comment]
@opoudjis 
> - Delete all files but the Readme in the riboseinc repository
> - Replace the Readme in the riboseinc repository with the message "Repository migrated to http://github.com/metanorma/X

We don't have http://github.com/riboseinc/X after migration. If you try to open http://github.com/riboseinc/X you will be redirected to http://github.com/metanorma/X. So we can't delete files or replace Readme.

**Comment by andrew2net** [comment]
@opoudjis @strogonoff done
